trigger:
- '*'

variables:
  buildConfiguration: 'Release'

stages:
- stage: 'Deploy_PRD'
  displayName: 'PRD Deploy the web application'
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-20.04'
    environment: PRD
    variables:
    - group: PRD_VARIABLE
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'          
          - template: .azdo/templates/azweb-deploy.yaml
            parameters:
              azureSubscription: 'Me-isarar1-rg-ado-tailspin-space-prd'
              appName: '$(AZURE_WEBAPP_NAME)'
              package: '$(Pipeline.Workspace)/drop/Release/*.zip'            