trigger:
- '*'

variables:
  buildConfiguration: 'Release'

stages:
- stage: 'Build'
  displayName: 'Build the web application'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-20.04'
      demands:
      - npm  
    variables:
      wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
      dotnetSdkVersion: '9.x'
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET SDK $(dotnetSdkVersion)'
      inputs:
        packageType: sdk
        version: '$(dotnetSdkVersion)'

    - task: DotNetCoreCLI@2
      displayName: 'Restore project dependencies'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    # - task: DotNetCoreCLI@2
    #   displayName: 'Build the project - Release'
    #   inputs:
    #     command: 'build'
    #     arguments: '--no-restore --configuration Release'
    #     projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Publish the project - Release'
      inputs:
        command: 'publish'
        projects: '**/*.csproj'
        publishWebProjects: false
        arguments: '--no-build --configuration Release --output $(Build.ArtifactStagingDirectory)/Release'
        zipAfterPublish: true
    
    - publish: $(Build.ArtifactStagingDirectory) # PublishPipelineArtifact@1
      displayName: 'Publish Artifact: drop'
      artifact: drop

- stage: 'Deploy_DEV'
  displayName: 'DEV Deploy the web application'
  dependsOn: Build
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-20.04'
    environment: DEV
    variables:
    - group: DEV_VARIABLE
    strategy:
      runOnce:
        deploy:
          steps:
          - template: .azdo/templates/azweb-deploy.yaml
            parameters:
              azureSubscription: 'Me-isarar1-rg-ado-tailspin-space-dev'
              appName: '$(AZURE_WEBAPP_NAME)'
              package: '$(Pipeline.Workspace)/drop/Release/*.zip'

- stage: 'Deploy_PRD'
  displayName: 'PRD Deploy the web application'
  dependsOn: Build
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-20.04'
    environment: PRD
    variables:
    - group: PRD_VARIABLE
    strategy:
      runOnce:
        deploy:
          steps:
          - template: .azdo/templates/azweb-deploy.yaml
            parameters:
              azureSubscription: 'Me-isarar1-rg-ado-tailspin-space-prd'
              appName: '$(AZURE_WEBAPP_NAME)'
              package: '$(Pipeline.Workspace)/drop/Release/*.zip'            